name: Run Pint Linter

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # PHP Setup
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Authenticate Composer
        run: composer config http-basic.spark.laravel.com ${{ secrets.SPARK_USERNAME}} ${{ secrets.SPARK_PASSWORD}}

      - name: Authenticate Nova
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME}} ${{ secrets.NOVA_PASSWORD}}
      # Composer Cache
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      # .env Setup
      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      # Run Linter
      - name: Run tests
        run: ./vendor/bin/pint --test
